### PR TITLE
Add "topic" tag in query

### PR DESCRIPTION
**Pull request by aeongdesu**
(if topic available) topic shows on the top when adds "topic" tag

Example
Screenshot_20210429-075920_Discord

Screenshot_20210429-080724

before

Screenshot_20210429-075934_Discord

Screenshot_20210429-080752

after (saves 8sec lol)

### CODE REVIEW

**Comment by skick1234** [comment]
image
.-.

**Comment by aeongdesu** [comment]
> image
> .-.

Screenshot_20210429-102656
Screenshot_20210429-102645


Well... try another song :)

**Comment by skick1234** [comment]
You should change this too.
https://github.com/distubejs/spotify/blob/f9531a06598cb9817630cb8fb7216d2528a6241b/index.js#L94

Anyway, I don't see any better results in my case. I will close this and you should use your fork if it can give you better results.

**Comment by ghost** [comment]
Not `topic` `"topic"`

**Comment by aeongdesu** [comment]
> Not `topic` `"topic"`

Thanks, please check again with `"topic"` @skick1234

**Comment by skick1234** [comment]
Not expected result
image

> Anyway, I don't see any better results in my case. I will close this and you should use your fork if it can give you better results.

**Pull request closed without merging**
